src/ui/__init__.py
from flask import Blueprint

ui = Blueprint('ui', __name__, template_folder="ui")

from . import routes

src/ui/routes.py
import traceback

from flask import render_template, request, url_for, g
from werkzeug.utils import redirect
from sqlalchemy import or_, not_

from src.spot.utils import SpotUtils
from src import db
from src.tasks.fetch import Fetch
from src.forms import SearchForm, UriForm, TrackForm, AlbumForm, ArtistForm
from src.ui import ui
from src.models import Track, Album, Artist, Location, Genre


@ui.route("/")
def index():
    queries = ["wack", "dope"]
    counts = [build_lyric_query_stat(q) for q in queries]
    stats = Fetch.stats()
    return render_template('ui/index.html', stats=stats, counts=counts)


@ui.route("/tracks")
def tracks():
    return render_class(Track, 'ui/tracks.html', 'ui.tracks')


@ui.route("/albums")
def albums():
    return render_class(Album, 'ui/albums.html', 'ui.albums')


@ui.route("/artists")
def artists():
    return render_class(Artist, 'ui/artists.html', 'ui.artists')


@ui.route("/locations")
def locations():
    return render_class(Location, 'ui/locations.html', 'ui.locations')


@ui.route("/tracks/<track_id>")
def get_track(track_id: int):
    return render_instance(Track, track_id, 'ui/track.html')


@ui.route("/albums/<album_id>")
def get_album(album_id: int):
    return render_instance(Album, album_id, 'ui/album.html')


@ui.route("/artists/<artist_id>")
def get_artist(artist_id: int):
    q = request.args.get('q') if request.args.get('q') else ""
    instance = Artist.query.get(artist_id)
    if instance:
        img = instance.get_img()
        dupes = Artist.query.filter(Artist.name.ilike(f"%{instance.name}%")).filter(not_(Artist.id == instance.id)).all()
        albums_count = len(instance.albums) if instance.albums else 0
        primary_tracks_count = len(instance.primary_tracks) if instance.primary_tracks else 0
        featured_tracks_count = len(instance.featured_tracks) if instance.featured_tracks else 0
        return render_template('ui/artist.html',
                               result=instance,
                               q=q,
                               albums_count=albums_count,
                               primary_tracks_count=primary_tracks_count,
                               featured_tracks_count=featured_tracks_count,
                               img=img if img else url_for('static', filename='img/__none.png'),
                               dupes=dupes)
    return redirect(url_for('.index'))


@ui.route("/genres")
def genres():
    return render_class(Genre, 'ui/genres.html', 'ui.genres')


@ui.route("/genres/<genre_id>")
def get_genre(genre_id: int):
    return render_instance(Genre, genre_id, 'ui/genre.html')


@ui.route("/locations/<location_id>")
def get_location(location_id: int):
    return render_instance(Location, location_id, 'ui/location.html')


@ui.route("/tracks/<track_id>/update", methods=["POST"])
def update_track(track_id: int):
    form = TrackForm(request.form)
    if form.validate_on_submit():
        _track = Track.query.filter_by(id=track_id).first()
        _track.name = form.name.data
        _track.lyrics = form.lyrics.data if form.lyrics.data and form.lyrics.data != "None" else None
        _track.lyrics_url = form.lyrics_url.data if form.lyrics_url.data and form.lyrics_url.data != "None" else None
        _track.lyrics_annotated = form.lyrics_annotated.data if form.lyrics_annotated.data and form.lyrics_annotated.data != "None" else None
        db.session.add(_track)
        db.session.commit()
        if not _track.lyrics_annotated:
            try:
                _ = Fetch.track_lyrics_annotate(_track.spot_uri)
            except Exception as e:
                print(f"Unable to annotate {_track.name}")
                traceback.print_tb(e.__traceback__)
    else:
        print(f"INVALID: {form.errors}")
    return redirect(url_for('ui.get_track', track_id=track_id))


@ui.route("/tracks/<track_id>/edit")
def edit_track(track_id: int):
    result = Track.query.filter_by(id=track_id).first()
    form = TrackForm(obj=result)
    return render_template('ui/track_edit.html', result=result, form=form)


@ui.route("/albums/<album_id>/update", methods=["POST"])
def update_album(album_id: int):
    form = AlbumForm(request.form)
    if form.validate_on_submit():
        _album = Album.query.filter_by(id=album_id).first()
        _album.name = form.name.data
        _album.release_date_string = form.release_date_string.data
        _album.release_date = SpotUtils.clean_up_date(_album.release_date_string)
        _album.dbp_uri = form.dbp_uri.data
        _album.wikipedia_uri = form.wikipedia_uri.data
        db.session.add(_album)
        db.session.commit()
    else:
        print(f"INVALID: {form.errors}")
    return redirect(url_for('ui.get_album', album_id=album_id))


@ui.route("/albums/<album_id>/edit")
def edit_album(album_id: int):
    result = Album.query.filter_by(id=album_id).first()
    form = AlbumForm(obj=result)
    return render_template('ui/album_edit.html', result=result, form=form)


@ui.route("/artists/<artist_id>/update", methods=["POST"])
def update_artist(artist_id: int):
    form = ArtistForm(request.form)
    if form.validate_on_submit():
        _artist = Artist.query.filter_by(id=artist_id).first()
        _artist.name = form.name.data
        _artist.dbp_uri = form.dbp_uri.data
        _artist.wikipedia_uri = form.wikipedia_uri.data
        db.session.add(_artist)
        db.session.commit()
    else:
        print(f"INVALID: {form.errors}")
    return redirect(url_for('ui.get_artist', artist_id=artist_id))


@ui.route("/artists/<artist_id>/merge/<dupe_id>")
def merge_artist(artist_id: int, dupe_id: int):
    _master = Artist.query.filter_by(id=artist_id).first()
    _dupe = Artist.query.filter_by(id=dupe_id).first()

    if _master and _dupe:
        print(_master)
        print(_dupe)
        for _track in _dupe.primary_tracks:
            print(_track)
        for _track in _dupe.featured_tracks:
            print(_track)
        for _section in _dupe.sections:
            print(_section)
        for _album in _dupe.albums:
            print(_album)

        db.session.add(_master)
        db.session.commit()
    else:
        print(f"Unable to merge {artist_id} and {dupe_id}")
    return {"job": "done"}


@ui.route("/artists/<artist_id>/edit")
def edit_artist(artist_id: int):
    result = Artist.query.filter_by(id=artist_id).first()
    form = ArtistForm(obj=result)
    return render_template('ui/artist_edit.html', result=result, form=form)


@ui.route('/search', methods=['GET', 'POST'])
def search():
    if not g.search_form.validate_on_submit():
        return redirect(url_for('.index'))
    return redirect(url_for('.search_results', query=g.search_form.search.data))


@ui.route('/search-results/<query>')
def search_results(query, in_xml=True):
    result = Track.query.filter(or_(
        Track.lyrics.ilike(f"% {query}%"),
        Track.lyrics.ilike(f"{query}%"),
        Track.lyrics.ilike(f"%\n{query}%")
    )).join(Album).order_by(Album.release_date)
    template = 'ui/xml_search_results.html' if in_xml else 'ui/search_results.html'
    return render_template(template, query=query, results=result.all(), number=result.count())


@ui.before_request
def before_request():
    g.search_form = SearchForm()
    g.uri_form = UriForm()


def pagination(_request) -> (int, int, int):
    offset = _request.args.get('offset') or 0
    offset = int(offset)
    start_page = int(offset/100)
    end_page = start_page + 100
    return offset, start_page, end_page


def render_class(model: db.Model, template: str, endpoint: str):
    q = request.args.get('q') or ""
    date = request.args.get('date') or ""
    offset, start_page, end_page = pagination(request)
    if date and model == Album:
        instances = model.query.filter(model.name.ilike(f"%{q}%")).filter(model.release_date_string == date).order_by(model.id).limit(100).offset(offset)
    else:
        instances = model.query.filter(model.name.ilike(f"%{q}%")).order_by(model.id).limit(100).offset(offset)
    count = model.query.count()
    return render_template(template, endpoint=endpoint, instances=instances, offset=offset, count=count, start_page=start_page, end_page=end_page, q=q)


def render_instance(model: db.Model, _id: int, template: str):
    q = request.args.get('q') if request.args.get('q') else ""
    instance = model.query.get(_id)
    if instance:
        dupes = model.query.filter(model.name.ilike(f"%{instance.name}%")).filter(not_(model.id == instance.id))
        img = instance.get_img()
        return render_template(template, result=instance, q=q, img=img if img else url_for('static', filename='img/__none.png'), dupes=dupes)
    return redirect(url_for('.index'))


def build_lyric_query_stat(query: str):
    return {"query": query, "count": Track.query.filter(Track.lyrics.contains(query)).count()}

src/templates/ui/_album.html
<div id="album_{{album.id}}" class="album">
    <div>
      {% if ("01-01" in album.release_date_string or album.release_date_string|length == 4) and album.dbp_uri %}
        <a id="{{album.spot_uri}}" class="red run-album-release-date">{{ album.release_date_string }}</a>
        <a href="{{album.dbp_uri}}" target="_blank" style="color: darkgray; font-style: italic"> [{{ album.dbp_uri }}]</a>
      {% else %}
        <a href="{{ url_for('ui.get_album', album_id=album.id) }}">
          <span class="track-release-date">{{ album.release_date_string }}</span>
        </a>
      {% endif %}
      {% for artist in album.artists %}
      <a href="{{ url_for('ui.get_artist', artist_id=artist.id) }}">
          <span class="track-artist">{{ artist.name }}</span>
      </a>
      {% endfor %}
      <a href="{{ url_for('ui.get_album', album_id=album.id) }}" class="album">[{{ album.name }}]</a>
      {% if album.last_updated is not none %}
        <span style="color: darkgray;">✓</span>
      {% else %}
        <a id="{{album.spot_uri}}" class="run-button run-album run-first">➢</a>
      {% endif %}

    </div>
    <div class="album-data">
        <a class="delete-button" onclick="deleteInstance('album', {{album.id}})">x</a>
        <span class="count">{{ album.lyrics_status() }}</span>
    </div>
</div>
<div class="album-progress">
    <div class="progress">
        <div class="progress-bar" role="progressbar" style="width: {{ album.lyrics_percentage() }}%" aria-valuenow="{{ album.lyrics_percentage() }}" aria-valuemin="0" aria-valuemax="100"></div>
        <div class="progress-bar bg-danger" role="progressbar" style="width: {{ album.lyrics_missed_percentage() }}%" aria-valuenow="{{ album.lyrics_missed_percentage() }}" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
</div>

src/templates/ui/_genre.html
<div id="genre_{{genre.id}}" class="genre">
    <div>
      <a href="{{ url_for('ui.get_genre', genre_id=genre.id) }}" class="genre">{{ genre.name }} {{ genre.artist_count() }}</a>
    </div>
</div>

src/templates/ui/_header.html
    <header id="{{result.spot_uri}}" class="header-with-img">
        <div class="header-rows">
            <div class="header-row-start">
                <div class="title-row">
                    {% block title_row %}{% endblock %}
                </div>
            </div>
            <div class="header-row-end">
                <div class="buttons-row">
                    <div class="buttons-row-start">
                        {% block buttons_row_start %}{% endblock %}
                    </div>
                    <div class="buttons-row-end">
                        {% block buttons_row_end %}{% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </header>

src/templates/ui/_location.html
<div id="location_{{location.id}}" class="location">
    <div>
      <a href="{{ url_for('ui.get_location', location_id=location.id) }}" class="location">{{ location.name }}</a>
    </div>
</div>

src/templates/ui/_merge_artist.html
<div class="artist merge-artist" id="dupe_{{artist.id}}">
    <a class="merge-button" href="#" onclick="mergeInstance({{result.id}}, {{artist.id}})">
        <img src="{{ url_for('static', filename='img/pr.svg') }}"/>
    </a>
    <a href="{{ url_for('ui.get_artist', artist_id=artist.id) }}">
        <span class="track-artist">{{ artist.name }}</span>
    </a>
    <span class="count">{{ artist.albums|length }} albums</span>
    <span> | </span>
    <span class="count">{{ artist.primary_tracks|length }} primary</span>
    <span> | </span>
    <span class="count">{{ artist.featured_tracks|length }} feat</span>
    <div class="artist-progress">
        <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: {{ artist.lyrics_percentage() }}%" aria-valuenow="{{ artist.lyrics_percentage() }}" aria-valuemin="0" aria-valuemax="100"></div>
            <div class="progress-bar bg-danger" role="progressbar" style="width: {{ artist.lyrics_missed_percentage() }}%" aria-valuenow="{{ artist.lyrics_missed_percentage() }}" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>
</div>

src/templates/ui/_pagination.html
<div class="pagination-wrapper">
    <ul class="pagination">
      {% if offset > 99 %}
        <li class="page-item">
          <a class="page-link" href="{{ url_for(endpoint)}}?offset=0&q={{q}}" aria-label="Previous">
            <span> << </span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="{{ url_for(endpoint)}}?offset={{offset - 100}}&q={{q}}" aria-label="Previous">
            <span> < </span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
      {% endif %}
      {% if (count - offset) > 100 %}
        <li class="page-item">
          <a class="page-link" href="{{ url_for(endpoint) }}?offset={{offset + 100}}&q={{q}}" aria-label="Next">
            <span> > </span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="{{ url_for(endpoint) }}?offset={{count - 100}}&q={{q}}" aria-label="Next">
            <span> >> </span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      {% endif %}
    </ul>
</div>

src/templates/ui/_track.html
<div class="track">
    <div>
        <a href="{{ url_for('ui.get_track', track_id=track.id) }}">
            <span class="track-release-date">{{ track.album.release_date_string }}</span>
        </a>
        {% for artist in track.album.artists %}
            {% if artist.name != "Various Artists" %}
                <a href="{{ url_for('ui.get_artist', artist_id=artist.id) }}">
                    <span class="track-artist">{{ artist.name }}</span>
                </a>
            {% endif %}
        {% endfor %}
        <a href="{{ url_for('ui.get_track', track_id=track.id) }}">
            <span class="track-title">"{{ track.render() }}"</span>
        </a>
        {% if track.adjusted_featured_artists() %}
            <span class="track-feat">feat. </span>
            {% for artist in track.adjusted_featured_artists() %}
            <a href="{{ url_for('ui.get_artist', artist_id=artist.id) }}">
                <span class="track-artist">{{ artist.name }}</span>
            </a>
            {% endfor %}
        {% endif %}

        {% if track.lyrics is not none %}
            <a class="geni-button" href="{{track.lyrics_url}}" target="_blank">
                <img src="{{ url_for('static', filename='img/genius-dark-sm.svg') }}"/>
            </a>
        {% elif track.lyrics is none and track.lyrics_url is not none %}
            <a id="{{track.spot_uri}}" class="run-button run-track">↻</span>
        {% else %}
            <a id="{{track.spot_uri}}" class="run-button run-track run-first">➢</a>
        {% endif %}

        <div style="float: right">
            {% if track.song_link() %}
                <a class="play-button" href="{{ track.song_link() }}" target="_blank">▶️</a>
            {% endif %}
        </div>
    </div>
    <div class="track-data">
        <a id="track_{{track.id}}" class="delete-button" onclick="deleteInstance('track', {{track.id}})">x</a>
    </div>
</div>

src/templates/ui/artist.html
{% extends "base.html" %}
{% block title %}{{ result.name }} ⋅ {% endblock %}

{% block head %}
    <style>
      header:before {
        background-image: url({{ img }});
        background-repeat: no-repeat;
        background-size: cover;
        background-position: 50% 20%;
        opacity: 0.15;
        content: ' ';
        display: block;
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        z-index: 1;
      }
      </style>
{% endblock %}

{% block content %}
    <header id="{{result.spot_uri}}"  class="header-with-img">
        <div class="header-rows">
            <div class="header-row-start">
                <div class="title-row">
                    <div class="h1 header-title">
                        {{ result.name }}
                        <a class="run-button run-artist">➢</a>
                    </div>
                    <a class="api-button" href="/api/v1/artists/{{ result.spot_uri }}" target="_blank">
                        <img src="{{ url_for('static', filename='img/cloud.svg') }}"/>
                    </a>
                </div>
            </div>
            <div class="header-row-end">
                <div class="locations-row">
                    {% if result.birthplace %}
                        <span class="location-label">Birthplace: </span>
                        <span class="location">{{ result.birthplace.name }}</span>
                    {% endif %}
                    {% if result.hometown %}
                        <span class="location-label">Hometown: </span>
                        <span class="location">{{ result.hometown.name }}</span>
                    {% endif %}
                </div>
                <div class="buttons-row">
                    <div class="buttons-row-start">
                        <a class="edit-button" href="{{ url_for('ui.edit_artist', artist_id=result.id) }}">✏️</a>
                        {% if result.wikipedia_uri %}
                        <span><a href="{{result.wikipedia_uri}}" target="_blank"><img class="metadata-img" height="25" width="25" src="{{ url_for('static', filename='img/wikipedia.png') }}"></a></span>
                        {% endif %}
                        {% if result.dbp_uri %}
                            <span><a href="{{result.dbp_uri}}" target="_blank"><img class="metadata-img" height="25" width="25" src="{{ url_for('static', filename='img/dbpedia.png') }}"></a></span>
                        {% endif %}
                    </div>
                    {% if albums_count > 0 %}
                        <div class="counts">
                            <h4>{{ albums_count }} Albums ⋅ {{ primary_tracks_count }} Tracks</h4>
                        </div>
                    {% endif %}
                    <a class="metadata-button run-artist-metadata">
                        <img class="metadata-img" height="25" width="25" src="{{ url_for('static', filename='img/location.svg') }}">
                    </a>
                </div>
            </div>
        </div>
    </header>
    <div class="progress">
        <div class="progress-bar" role="progressbar" style="width: {{ result.lyrics_percentage() }}%" aria-valuenow="{{ result.lyrics_percentage() }}" aria-valuemin="0" aria-valuemax="100">{{ result.lyrics_percentage() }}% DONE</div>
        <div class="progress-bar bg-danger" role="progressbar" style="width: {{ result.lyrics_missed_percentage() }}%" aria-valuenow="{{ result.lyrics_missed_percentage() }}" aria-valuemin="0" aria-valuemax="100">{{ result.lyrics_missed_percentage() }}% MISSED</div>
    </div>
    {% if albums_count > 0 %}
        <ul class="list-group">
            {% for album in result.albums|sort(attribute='release_date') %}
                <li class="list-group-item">
                    {% include "ui/_album.html" %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        {% if primary_tracks_count > 0 %}
            <h4 class="tracks-label">{{ primary_tracks_count }} Primary Tracks </h4>
            <ul class="list-group">
                {% for track in result.primary_tracks|sort(attribute='album.release_date') %}
                    <li class="list-group-item">
                        {% include "ui/_track.html" %}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        {% if featured_tracks_count > 0 %}
            <h4 class="tracks-label">{{ featured_tracks_count }} Featured Tracks</h4>
            <ul class="list-group">
                {% for track in result.featured_tracks|sort(attribute='album.release_date') %}
                    <li class="list-group-item">
                        {% include "ui/_track.html" %}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endif %}
    <div class="genres">
        {% for genre in result.genres %}
            <a href="{{ url_for('ui.get_genre', genre_id=genre.id) }}" class="genre btn btn-primary btn-sm active">{{ genre.name }}</a>
        {% endfor %}
    </div>
    <div class="dupes">
        <ul class="list-group">
            {% for artist in dupes %}
              <li class="list-group-item">
                {% include "ui/_merge_artist.html" %}
              </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

{% block scripts %}
    <script>
  function runReleaseDate(s) {
      let uri = $(s).attr('id');
      let endpoint = `/api/v1/albums/${uri}/release-date/run?update=True`;
        $.get(endpoint)
         .done(function(album) {
          console.log(`Successfully run release date update for ${uri}`);
          let releaseDate = album.release_date_string;
          console.log(releaseDate);
          $(s).html(`<span>${releaseDate}</span>`);
          $(s).removeClass("red");
          $(s).removeClass("run-album-release-date");
          $(s).next().remove("a");
      }).fail(function() { console.log(`Failed to run ${uri}`); });
  }

  $("a.run-album-release-date")
     .click(function(){
       runReleaseDate(this);
     });
     </script>
{% endblock %}

src/templates/ui/artist_edit.html
{% extends "base.html" %}
{% block title %}{{ result.name }} ⋅ {% endblock %}


{% block head %}
    <style>
      header:before {
        background-image: url({{ img }});
        background-repeat: no-repeat;
        background-size: cover;
        background-position: 50% 20%;
        opacity: 0.15;
        content: ' ';
        display: block;
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        z-index: 1;
      }
      </style>
{% endblock %}

{% block content %}
    <header id="{{result.spot_uri}}"  class="header-with-img">
        <div class="header-rows">
            <div class="header-row-start">
                <div class="title-row">
                    <div class="h1 header-title">
                        {{ result.name }}
                        <a class="run-button run-artist">➢</a>
                    </div>
                    <a class="api-button" href="/api/v1/artists/{{ result.spot_uri }}" target="_blank">
                        <img src="{{ url_for('static', filename='img/cloud.svg') }}"/>
                    </a>
                </div>
            </div>
            <div class="header-row-end">
                <div class="locations-row">
                    {% if result.birthplace %}
                        <span class="location-label">Birthplace: </span>
                        <span class="location">{{ result.birthplace.name }}</span>
                    {% endif %}
                    {% if result.hometown %}
                        <span class="location-label">Hometown: </span>
                        <span class="location">{{ result.hometown.name }}</span>
                    {% endif %}
                </div>
                <div class="buttons-row">
                    <div class="buttons-row-start">
                        <a class="edit-button" href="{{ url_for('ui.edit_artist', artist_id=result.id) }}">✏️</a>
                        {% if result.wikipedia_uri %}
                        <span><a href="{{result.wikipedia_uri}}" target="_blank"><img class="metadata-img" height="25" width="25" src="{{ url_for('static', filename='img/wikipedia.png') }}"></a></span>
                        {% endif %}
                        {% if result.dbp_uri %}
                            <span><a href="{{result.dbp_uri}}" target="_blank"><img class="metadata-img" height="25" width="25" src="{{ url_for('static', filename='img/dbpedia.png') }}"></a></span>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div>
        <form method="POST" action="{{ url_for('ui.update_artist', artist_id=result.id) }}">
            {{ form.hidden_tag() }}
            <div class="form-group">
                <label>Name</label>
                {{ form.name() }}
            </div>
            <div class="form-group">
                <label>DBPedia URI</label>
                {{ form.dbp_uri() }}
            </div>
            <div class="form-group">
                <label>Wikipedia URI</label>
                {{ form.wikipedia_uri() }}
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

{% endblock %}

{% block scripts %}
    <script>
    $(document).ready(function () {
        $('input').addClass('form-control');
        console.log("DONE!");
    });
    </script>
{% endblock %}

src/templates/ui/artists.html
{% extends "base.html" %}

{% block content %}
<div class="container">

    <ul class="list-group">
        {% for artist in instances %}
          <li class="list-group-item">
            {% include "ui/_artist.html" %}
          </li>
        {% endfor %}
    </ul>

</div>
{% endblock %}

src/templates/ui/genres.html
{% extends "base.html" %}

{% block content %}
<div class="container">

    <ul class="list-group">
        {% for genre in instances %}
          <li class="list-group-item">
            {% include "ui/_genre.html" %}
          </li>
        {% endfor %}
    </ul>

    {% include 'ui/_pagination.html' %}

</div>
{% endblock %}

src/templates/ui/index.html
{% extends "base.html" %}

{% block head %}
    <style>
      html {
        background-image: url({{ url_for('static', filename='img/cold-crush-dim.jpg') }});
        background-repeat: no-repeat;
        background-size: cover;
      }
    </style>
{% endblock %}

{% block content %}
    <table class="table table-dark" style="background-color: transparent;">
        <thead>
            <tr><th scope="col">Type</th><th scope="col">Count</th></tr>
        </thead>
        <tbody>
            {% for row in stats %}
                <tr><td>{{ row.type }}</td><td>{{ row.count }}</td></tr>
            {% endfor %}
        </tbody>
    </table>

<!--    <div>{{ counts }}</div>-->
{% endblock %}

src/templates/ui/search_results.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="h1">{{ query }}</div>
    <div class="h5"> ({{ results|length }} results)</div>
        {% for result in results %}
            <div class="h5">
                <span class="release-date">{{ result.album.release_date_string }}</span>
                {% for artist in result.primary_artists %}
                    <span class="artist">{{ artist.name }}</span>
                {% endfor %}
                <span class="song-title"><a href="{{ url_for('ui.get_track', track_id=result.id) }}?q={{ query }}" target="_blank">"{{result.render()}}"</a></span>
                {% if result.featured_artists %}
                    feat.
                    {% for f in result.featured_artists %}
                        <span class="feat-artist">{{ f.name }}</span>
                    {% endfor %}
                {% endif %}
                <span class="album">[ {{ result.album.name }} ]</span>
                {% for lyric in result.filter_lyrics(query) %}
                    <div class="lyric">{{ lyric|replace(query, "<span class='query'>" + query + "</span>")|safe }}</div>
                {% endfor %}
            </div>
        {% endfor %}
</div>
{% endblock %}

src/templates/ui/track_edit.html
{% extends "base.html" %}
{% block title %}{{ result.artist_and_track_name() }} ⋅ {% endblock %}

{% block head %}
    <style>
      header:before {
        background-image: url({{ img }});
        background-repeat: no-repeat;
        background-size: cover;
        background-position: 50% 20%;
        opacity: 0.15;
        content: ' ';
        display: block;
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        z-index: 1;
      }
      </style>
{% endblock %}

{% block content %}
    <header id="{{result.spot_uri}}" class="header-with-img">
        <div class="header-rows">
            <div class="header-row-start">
                <div class="title-row">
                    <div class="h1 header-title">
                        {{ result.artist_and_track_name() }}
                    </div>
                    <a class="api-button" href="/api/v1/tracks/{{ result.spot_uri }}" target="_blank">
                        <img src="{{ url_for('static', filename='img/cloud.svg') }}"/>
                    </a>
                </div>
            </div>
            <div class="header-row-end">

            </div>
        </div>
    </header>

    <div>
        <form method="POST" action="{{ url_for('ui.update_track', track_id=result.id) }}">
            {{ form.hidden_tag() }}
            <div class="form-group">
                <label for="name" class="sr-only">Name</label>
                <input name="name" type="text" class="form-control" id="name" value="{{ form.name.data }}"/>
            </div>
            <div class="form-group">
                <label for="url" class="sr-only">URL</label>
                <input name="url" type="text" class="form-control" id="url" value="{{ form.lyrics_url.data }}"/>
            </div>
            <div class="form-group">
                <textarea name="lyrics" class="form-control" id="lyrics" rows="20">{{ form.lyrics.data }}</textarea>
            </div>
            <div class="form-group">
                <textarea name="lyrics_annotated" class="form-control" id="lyrics_annotated" rows="20">{{ form.lyrics_annotated.data }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

{% endblock %}